path,msg_id,msg,alerts,chosen,In which repository the modification was done?,In which pull request the modification was done?,Do you consider the removed alert harmful?,Why do you consider it harmful (or harmless)?,"What is the code quality (1 lowest, 10 best)? Code quality refers to the code prior to the pull request.",Why do you consider the code quality as such?,"What is the expected benefit(1 – negative, 5 – neutral, 10 – great)?",Why do you consider the pull request to improve the code (or not improve it)?
src\stacosys\run.py,W0718,broad-exception-caught,1,1,kianby/stacosys, ,Discuss,"run.py catches Exception in line 103. The try section just calls main. The function load_and_validate_config might raise FileNotFoundError or ValueError. However, I could not know for sure which other exceptions are suitable here.",7,regular, , 
src\stacosys\service\mail.py,W0718,broad-exception-caught,1,1,kianby/stacosys,https://github.com/kianby/stacosys/pull/22,Yes," Catching Exception might hide unexpected exceptions, like those that might be raised due to future modification. Therefore, it is recommended to narrow the exceptions.  The method send of the class Mailer catches Exception in line 57. MIMEText does not raise exceptions (if not using attachments). See https://docs.python.org/3/library/email.mime.html  Most code is handled in an inner exception handling. In order to catch exception from SMTP_SSL I used SMTPException See https://docs.python.org/3/library/smtplib.html ",9,"clean, small, focused class",6,A more focused exception
