path,msg_id,msg,alerts,chosen,In which repository the modification was done?,In which pull request the modification was done?,Do you consider the removed alert harmful?,Why do you consider it harmful (or harmless)?,"What is the code quality (1 lowest, 10 best)? Code quality refers to the code prior to the pull request.",Why do you consider the code quality as such?,"What is the expected benefit(1 – negative, 5 – neutral, 10 – great)?",Why do you consider the pull request to improve the code (or not improve it)?
neutron_lib\db\model_query.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\db\utils.py,W0718, broad-exception-caught,1,1, , , , , , , , 
neutron_lib\api\validators\__init__.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\constants.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\api\validators\allowedaddresspairs.py,R0912, too-many-branches,1,1, , , , , , , , 
neutron_lib\rpc.py,W0718, broad-exception-caught,1,1, , , , , , , , 
neutron_lib\services\base.py,W0107,unnecessary-pass,2,1, , , , , , , , 
neutron_lib\utils\helpers.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\services\qos\base.py,W0125,using-constant-test,1,1, , , , , , , , 
neutron_lib\exceptions\__init__.py,W0718, broad-exception-caught,1,1, , , , , , , , 
neutron_lib\plugins\ml2\api.py,C0302, too-many-lines,1,1, , , , , , , , 
neutron_lib\utils\upgrade_checks.py,W0107,unnecessary-pass,1,1, , , , , , , , 
neutron_lib\api\converters.py,W0718, broad-exception-caught,1,1, , , , , , , , 
neutron_lib\api\definitions\bgpvpn.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\api\definitions\qos_pps_minimum_rule.py,C0325, superfluous-parens,1,1, , , , , , , , 
neutron_lib\callbacks\manager.py,W0718, broad-exception-caught,1,1, , , , , , , , 
neutron_lib\db\model_query.py,R0912, too-many-branches,2,0, , , , , , , , 
neutron_lib\db\utils.py,C0325, superfluous-parens,1,0, , , , , , , , 
neutron_lib\api\validators\__init__.py,C0302, too-many-lines,1,0, , , , , , , , 
neutron_lib\api\validators\__init__.py,R0911, too-many-return-statements,1,0, , , , , , , , 
neutron_lib\api\validators\__init__.py,W0718, broad-exception-caught,4,0, , , , , , , , 
neutron_lib\plugins\utils.py,W0718, broad-exception-caught,4,0, , , , , , , , 
neutron_lib\exceptions\__init__.py,W0107,unnecessary-pass,3,0, , , , , , , , 
neutron_lib\plugins\ml2\api.py,W0107,unnecessary-pass,29,0, , , , , , , , 
neutron_lib\db\api.py,W0718, broad-exception-caught,3,0, , , , , , , , 
releasenotes\source\conf.py,R0801, duplicate-code,167,0, , , , , , , , 
