path,msg_id,msg,alerts,chosen,In which repository the modification was done?,In which pull request the modification was done?,Do you consider the removed alert harmful?,Why do you consider it harmful (or harmless)?,"What is the code quality (1 lowest, 10 best)? Code quality refers to the code prior to the pull request.",Why do you consider the code quality as such?,"What is the expected benefit(1 – negative, 5 – neutral, 10 – great)?",Why do you consider the pull request to improve the code (or not improve it)?
openstackclient\identity\v3\mapping.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_flavor_profile.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\default_security_group_rule.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\identity\v3\region.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\access_rule.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\application_credential.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\client.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\volume\v3\volume.py,C0302, too-many-lines,1,1, , , , , , , , 
openstackclient\identity\v3\ec2creds.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\local_ip_association.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v3\volume_transfer_request.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\user.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\network\common.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\common\clientmanager.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v2\image.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\identity\v3\identity_provider.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\service_provider.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v1\volume.py,R0915, too-many-statements,1,1, , , , , , , , 
examples\common.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\keypair.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\ndp_proxy.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network.py,R0912, too-many-branches,2,1, , , , , , , , 
openstackclient\compute\v2\server_migration.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\identity\v3\service.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\utils.py,R1703, simplifiable-if-statement,2,1, , , , , , , , 
openstackclient\volume\v3\volume_backup.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\network\v2\network_qos_rule.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\network\v2\network_meter_rule.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_segment_range.py,R0916, too-many-boolean-expressions,1,1, , , , , , , , 
openstackclient\identity\v3\credential.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\policy.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v1\image.py,R1702, too-many-nested-blocks,1,1, , , , , , , , 
openstackclient\volume\v2\consistency_group.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\network\v2\security_group_rule.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\image\v2\metadef_resource_type_association.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v2\volume_transfer_request.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v1\volume_backup.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\volume\v2\consistency_group_snapshot.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\common\availability_zone.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\compute\v2\server_group.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\router.py,C0302, too-many-lines,1,1, , , , , , , , 
openstackclient\volume\v2\volume_type.py,R0915, too-many-statements,1,1, , , , , , , , 
openstackclient\network\v2\floating_ip_port_forwarding.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v3\volume_message.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\flavor.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\network\v2\network_rbac.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\registered_limit.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\common\quota.py,R0915, too-many-statements,1,1, , , , , , , , 
openstackclient\compute\v2\usage.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\role.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\l3_conntrack_helper.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\endpoint.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_trunk.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\aggregate.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\address_group.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\local_ip.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v2\volume.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\compute\v2\server.py,W0107,unnecessary-pass,1,1, , , , , , , , 
openstackclient\network\v2\network_flavor.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\common\module.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\port.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\subnet.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v3\volume_type.py,R0912, too-many-branches,2,1, , , , , , , , 
openstackclient\identity\v3\domain.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\service.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_qos_policy.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_segment.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\server_event.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\identity\v3\endpoint_group.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\network_meter.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\federation_protocol.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v2\cache.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\identity\v3\role.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v3\volume_snapshot.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\user.py,W0718, broad-exception-caught,2,1, , , , , , , , 
openstackclient\identity\v3\trust.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\role_assignment.py,R1719, simplifiable-if-expression,1,1, , , , , , , , 
openstackclient\identity\v3\project.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\common.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v2\metadef_namespaces.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\endpoint.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v2\metadef_objects.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\address_scope.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\agent.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\network\v2\subnet_pool.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\ec2creds.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\volume\v1\volume_transfer_request.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\limit.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\image\v2\metadef_properties.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v3\consumer.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\identity\v2_0\project.py,W0718, broad-exception-caught,1,1, , , , , , , , 
openstackclient\compute\v2\service.py,R0912, too-many-branches,1,1, , , , , , , , 
openstackclient\network\v2\default_security_group_rule.py,W0718, broad-exception-caught,1,0, , , , , , , , 
releasenotes\source\conf.py,R0801, duplicate-code,2052,0, , , , , , , , 
openstackclient\volume\v3\volume.py,R0912, too-many-branches,2,0, , , , , , , , 
openstackclient\volume\v3\volume.py,R0915, too-many-statements,2,0, , , , , , , , 
openstackclient\volume\v3\volume.py,W0718, broad-exception-caught,16,0, , , , , , , , 
openstackclient\identity\v3\user.py,W0718, broad-exception-caught,1,0, , , , , , , , 
openstackclient\network\common.py,W0107,unnecessary-pass,4,0, , , , , , , , 
openstackclient\image\v2\image.py,C0302, too-many-lines,1,0, , , , , , , , 
openstackclient\image\v2\image.py,R0912, too-many-branches,4,0, , , , , , , , 
openstackclient\image\v2\image.py,R0915, too-many-statements,2,0, , , , , , , , 
openstackclient\volume\v1\volume.py,R0912, too-many-branches,2,0, , , , , , , , 
openstackclient\volume\v1\volume.py,W0718, broad-exception-caught,10,0, , , , , , , , 
openstackclient\network\v2\network.py,R0915, too-many-statements,1,0, , , , , , , , 
openstackclient\identity\v3\group.py,W0718, broad-exception-caught,3,0, , , , , , , , 
openstackclient\volume\v3\volume_backup.py,W0718, broad-exception-caught,5,0, , , , , , , , 
openstackclient\network\v2\network_segment_range.py,R1719, simplifiable-if-expression,1,0, , , , , , , , 
openstackclient\network\v2\network_segment_range.py,W0718, broad-exception-caught,1,0, , , , , , , , 
openstackclient\image\v1\image.py,R0912, too-many-branches,2,0, , , , , , , , 
openstackclient\image\v1\image.py,W0718, broad-exception-caught,1,0, , , , , , , , 
openstackclient\image\v2\metadef_resource_type_association.py,R1719, simplifiable-if-expression,1,0, , , , , , , , 
openstackclient\common\availability_zone.py,W0706, try-except-raise,1,0, , , , , , , , 
openstackclient\network\v2\router.py,R0912, too-many-branches,2,0, , , , , , , , 
openstackclient\network\v2\router.py,W0718, broad-exception-caught,1,0, , , , , , , , 
openstackclient\volume\v2\volume_type.py,R0912, too-many-branches,1,0, , , , , , , , 
openstackclient\volume\v2\volume_type.py,W0718, broad-exception-caught,13,0, , , , , , , , 
openstackclient\compute\v2\flavor.py,W0718, broad-exception-caught,8,0, , , , , , , , 
openstackclient\common\quota.py,R0912, too-many-branches,1,0, , , , , , , , 
openstackclient\network\v2\network_agent.py,W0718, broad-exception-caught,3,0, , , , , , , , 
openstackclient\volume\v1\qos_specs.py,W0718, broad-exception-caught,4,0, , , , , , , , 
openstackclient\volume\v2\volume.py,R0915, too-many-statements,1,0, , , , , , , , 
openstackclient\volume\v2\volume.py,W0718, broad-exception-caught,16,0, , , , , , , , 
openstackclient\compute\v2\server.py,C0302, too-many-lines,1,0, , , , , , , , 
openstackclient\compute\v2\server.py,R0912, too-many-branches,7,0, , , , , , , , 
openstackclient\compute\v2\server.py,R0915, too-many-statements,4,0, , , , , , , , 
openstackclient\compute\v2\server.py,W0718, broad-exception-caught,8,0, , , , , , , , 
openstackclient\network\v2\port.py,C0302, too-many-lines,1,0, , , , , , , , 
openstackclient\network\v2\port.py,R0912, too-many-branches,4,0, , , , , , , , 
openstackclient\network\v2\port.py,R0915, too-many-statements,3,0, , , , , , , , 
openstackclient\network\v2\subnet.py,R0912, too-many-branches,1,0, , , , , , , , 
openstackclient\network\v2\subnet.py,R0915, too-many-statements,1,0, , , , , , , , 
openstackclient\volume\v1\volume_type.py,W0718, broad-exception-caught,7,0, , , , , , , , 
openstackclient\volume\v3\volume_type.py,R0915, too-many-statements,1,0, , , , , , , , 
openstackclient\volume\v3\volume_type.py,W0718, broad-exception-caught,13,0, , , , , , , , 
openstackclient\volume\v2\volume_backup.py,W0718, broad-exception-caught,4,0, , , , , , , , 
openstackclient\volume\v2\qos_specs.py,W0718, broad-exception-caught,4,0, , , , , , , , 
openstackclient\volume\v3\volume_group_type.py,W0718, broad-exception-caught,3,0, , , , , , , , 
openstackclient\common\extension.py,W0718, broad-exception-caught,4,0, , , , , , , , 
openstackclient\network\v2\subnet_pool.py,R0912, too-many-branches,1,0, , , , , , , , 
openstackclient\volume\v1\volume_snapshot.py,W0718, broad-exception-caught,5,0, , , , , , , , 
openstackclient\compute\v2\service.py,W0718, broad-exception-caught,3,0, , , , , , , , 
openstackclient\volume\v2\volume_snapshot.py,W0718, broad-exception-caught,6,0, , , , , , , , 
